### PR TITLE
Update geo-types to 0.7

### PR DESCRIPTION
**Pull request by JonathanPlasse**
Hi,

Thank you for this project.

I updated `geo-types` to the version 0.7 as it was incompatible with new versions of `geo`.
I also fixed clippy warnings.

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
Hi @anlumo, are you interested in this PR, or should I close it?

**Comment by anlumo** [comment]
I somehow missed this, merged! Thank you for the contribution.

**Comment by JonathanPlasse** [comment]
You are welcome.

**Comment by JonathanPlasse** [comment]
Hi @anlumo, could you publish the new version on crates.io?

**Comment by anlumo** [comment]
I'll look into it!

**Comment by JonathanPlasse** [comment]
Thank you.

**Pull request merged**
